### ISSUE TITLE
crashes during PCA

### ISSUE THREAD

**Issue by neuromusic** [klusta-team/spikedetekt2#20]
```
2015-01-21 12:15:27  100% complete, 1h 15m 21s elapsed, 0s remaining. 937518 spikes found.
2015-01-21 12:15:42  Traceback (most recent call last):
  File "/usr/local/anaconda/envs/klusta/bin/klusta", line 9, in <module>
    load_entry_point('klustaviewa==0.3.0.beta4', 'console_scripts', 'klusta')()
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 290, in main
    runsd=runsd, runkk=runkk)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 260, in run_all
    run_spikedetekt(prm_filename, dir=dir, debug=debug)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 115, in run_spikedetekt
    _debug=debug)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/main.py", line 267, in run
    save_features(experiment, **prm)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/main.py", line 116, in save_features
    pcs = compute_pcs(waveforms_subset, npcs=npcs, masks=masks)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/processing/pca.py", line 31, in compute_pcs
    for i in range(x.shape[-1])])
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/processing/pca.py", line 43, in compute_pcs
    vals, vecs = np.linalg.eigh(cov_ss)
  File "/usr/local/anaconda/envs/klusta/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1206, in eigh
    _assertNdSquareness(a)
  File "/usr/local/anaconda/envs/klusta/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 212, in _assertNdSquareness
    raise LinAlgError('Last 2 dimensions of the array must be square')
LinAlgError: Last 2 dimensions of the array must be square
None
```

**Comment by neuromusic** [comment]
this was on 0.2.0dev. pulled the latest (and the latest kwiklib) & removed dead channels from the probe file. I should know if it works soon.

**Comment by neuromusic** [comment]
using latest & removing dead channels worked just fine.
