### ISSUE TITLE
error if extract_s_before + extract_s_after <> 20

### ISSUE THREAD

**Issue by neuromusic** [klusta-team/spikedetekt2#21]
If the sum of `extract_s_before` and `extract_s_after` do no equal 20, SpikeDetekt2 throws a ValueError...

```
2015-01-25 09:56:34  Traceback (most recent call last):
  File "/usr/local/anaconda/envs/klusta/bin/klusta", line 9, in <module>
    load_entry_point('klustaviewa==0.3.0.beta4', 'console_scripts', 'klusta')()
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 303, in main
    runsd=runsd, runkk=runkk, convert_only=convert_only)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 264, in run_all
    run_spikedetekt(prm_filename, dir=dir, debug=debug, convert_only=convert_only)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/script.py", line 117, in run_spikedetekt
    _debug=debug, convert_only=convert_only)
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/main.py", line 272, in run
    [add_waveform(experiment, waveform) for waveform in sorted(waveforms)]
  File "/usr/local/home/jkiggins/Code/spikedetekt2/spikedetekt2/core/main.py", line 75, in add_waveform
    masks=waveform.masks,
  File "/usr/local/home/jkiggins/Code/kwiklib/kwiklib/dataio/experiment.py", line 438, in add
    add_spikes(self._files, channel_group_id=self.channel_group_id, **kwargs)
  File "/usr/local/home/jkiggins/Code/kwiklib/kwiklib/dataio/kwik.py", line 828, in add_spikes
    ds_waveforms_raw.append(waveforms_raw.astype(np.int16))
  File "/usr/local/anaconda/envs/klusta/lib/python2.7/site-packages/tables/earray.py", line 211, in append
    self._check_shape_append(nparr)
  File "/usr/local/anaconda/envs/klusta/lib/python2.7/site-packages/tables/earray.py", line 189, in _check_shape_append
    "dimension %d") % (self._v_pathname, i))
ValueError: the shapes of the appended object and the ``/channel_groups/0/waveforms_raw`` EArray differ in non-enlargeable dimension 1
```

**Comment by neuromusic** [comment]
same as #16 which was fixed with klusta-team/kwiklib#18
